from django.db import models

# Create your models here.
class Products(models.Model): 
    ID =models.AutoField(primary_key=True,db_column='ID')
    Type=models.CharField(max_length=250,db_column='Type') 
    SKU=models.CharField(max_length=250,db_column='SKU')  
    Name=models.CharField(max_length=250,db_column='Name')
    Published=models.BigIntegerField(db_column='Published')
    Is_featured=models.BigIntegerField(db_column='Is featured?')
    Visibility_in_catalog=models.CharField(max_length=250,db_column='Visibility in catalog')
    Short_description=models.CharField(max_length=250,db_column='Short description')
    description=models.TextField(models.TextField(db_column='description'))
    Date_sale_price_starts=models.FloatField(db_column='Date sale price starts')
    Date_sale_price_ends=models.FloatField(db_column='Date sale price ends')
    Tax_status=models.FloatField(db_column='Tax status')
    Tax_class=models.FloatField(db_column='Tax class')
    In_stock=models.BigIntegerField(db_column='In stock?')
    Stock=models.BigIntegerField(db_column='Stock')
    Backorders_allowed=models.BigIntegerField(db_column='Backorders allowed?')
    Sold_individually=models.BigIntegerField(db_column='Sold individually?')
    Weight=models.FloatField(db_column='Weight (lbs)')
    Length=models.FloatField(db_column='Length (in)')
    Width=models.FloatField(db_column='Width (in)')
    Height=models.FloatField(db_column='Height (in)')
    Allow_customer_reviews=models.BigIntegerField(db_column='Allow customer reviews?')
    Purchase_note=models.FloatField(db_column='Purchase note')
    Sale_price=models.FloatField(db_column='Sale price')
    Regular_price=models.FloatField(db_column='Regular price')
    Categories=models.CharField(max_length=250,db_column='Categories')
    Tags=models.FloatField(db_column='Tags')
    Shipping_class=models.FloatField(db_column='Shipping class')
    Images=models.CharField(max_length=250,db_column='Images')
    Download_limit=models.FloatField(db_column='Download limit')
    Download_expiry_days=models.FloatField(db_column='Download expiry days')
    Parent=models.CharField(max_length=250,db_column='Parent')
    Grouped_products=models.FloatField(db_column='Grouped products')
    Upsells=models.FloatField(db_column='Upsells')
    Cross_sells=models.FloatField(db_column='Cross-sells')
    External_URL=models.FloatField(db_column='External URL')
    Button_text=models.FloatField(db_column='Button text')
    Position=models.FloatField(db_column='Position')
    Attribute_1_name=models.CharField(max_length=250,db_column='Attribute 1 name')
    Attribute_1_value=models.CharField(max_length=250,db_column='Attribute 1 value(s)') 
    Attribute_2_name=models.CharField(max_length=250,db_column='Attribute 2 name') 
    Attribute_2_value=models.CharField(max_length=250,db_column='Attribute 2 value(s)') 
    Attribute_3_name=models.CharField(max_length=250,db_column='Attribute 3 name') 
    Attribute_3_value=models.CharField(max_length=250,db_column='Attribute 3 value(s)') 
    Attribute_4_name=models.CharField(max_length=250,db_column='Attribute 4 name') 
    Attribute_4_value=models.CharField(max_length=250,db_column='Attribute 4 value(s)') 
    Attribute_5_name=models.CharField(max_length=250,db_column='Attribute 5 name') 
    Attribute_5_value=models.CharField(max_length=250,db_column='Attribute 5 value(s)') 
    Meta_wpcom_is_markdown=models.FloatField(db_column='Meta: _wpcom_is_markdown')
    Download_1_name=models.FloatField(db_column='Download 1 name')
    Download_1_URL=models.FloatField(db_column='Download 1 URL')
    Download_2_name=models.FloatField(db_column='Download 2 name')
    Download_2_URL=models.FloatField(db_column='Download 2 URL')


    def __str__(self): 
        return str(self.ID)
   
    class Meta:
        db_table = 'Products'
