# Generated by Django 3.2.19 on 2023-06-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products_updates',
            fields=[
                ('Id_update', models.AutoField(db_column='Id_update', primary_key=True, serialize=False)),
                ('Updated_at', models.DateTimeField(db_column='Updated_at')),
                ('Product_name', models.CharField(db_column='Product_name', max_length=250)),
                ('Product_description', models.TextField(db_column='Product_description')),
                ('Product_id', models.CharField(db_column='Product_id', max_length=15)),
            ],
            options={
                'db_table': 'Products_updates_log',
            },
        ),
    ]
